filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/app/*.log
    fields:
      app: ai-budget
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

setup.template.name: "ai-budget-logs"
setup.template.pattern: "ai-budget-logs-*"
setup.template.enabled: false
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "elastic123!@#"
  index: "ai-budget-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644