spring:
  datasource:
    url: jdbc:mysql://localhost:3307/newsdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6380

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  secretKey: gisung-project-ai-budget-jwt-secret-key-is-mine
  access:
    expiration: 1800000
  refresh:
    expiration: 1209600000